include(CTest)
enable_testing()

add_executable(test_matrix ${CMAKE_CURRENT_SOURCE_DIR}/solvers/algorithm_x/test_matrix.c)
add_executable(test_node ${CMAKE_CURRENT_SOURCE_DIR}/solvers/algorithm_x/test_node.c)
add_executable(test_puzzle ${CMAKE_CURRENT_SOURCE_DIR}/puzzle/test_puzzle.c)
add_executable(test_singles ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_singles.c)
add_executable(test_subsets ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_subsets.c)
add_executable(test_locked_candidates ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_locked_candidates.c)
add_executable(test_x_wings ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_x_wing.c)
add_executable(test_skyscrapers ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_skyscraper.c)
add_executable(test_chute_remote_pairs ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_chute_remote_pairs.c)
add_executable(test_simple_colors ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_simple_colors.c)
add_executable(test_w_wings ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_w_wings.c)
add_executable(test_xy_wings ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_xy_wings.c)
add_executable(test_xyz_wings ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_xyz_wings.c)
add_executable(test_swordfish ${CMAKE_CURRENT_SOURCE_DIR}/solvers/logical/test_swordfish.c)

target_link_libraries(test_matrix unity algorithm_x_solver)
target_link_libraries(test_node unity algorithm_x_solver)
target_link_libraries(test_puzzle unity puzzle)
target_link_libraries(test_singles unity puzzle logical_solver)
target_link_libraries(test_subsets unity puzzle logical_solver)
target_link_libraries(test_locked_candidates unity puzzle logical_solver)
target_link_libraries(test_x_wings unity puzzle logical_solver)
target_link_libraries(test_skyscrapers unity puzzle logical_solver)
target_link_libraries(test_simple_colors unity puzzle logical_solver)
target_link_libraries(test_chute_remote_pairs unity puzzle logical_solver)
target_link_libraries(test_w_wings unity puzzle logical_solver)
target_link_libraries(test_xy_wings unity puzzle logical_solver)
target_link_libraries(test_xyz_wings unity puzzle logical_solver)
target_link_libraries(test_swordfish unity puzzle logical_solver)

add_test(matrix_tests test_matrix)
add_test(node_tests test_node)
add_test(puzzle_tests test_puzzle)
add_test(singles_tests test_singles)
add_test(subsets_tests test_subsets)
add_test(locked_candidates test_locked_candidates)
add_test(x_wings test_x_wings)
add_test(skyscrapers test_skyscrapers)
add_test(simple_colors test_simple_colors)
add_test(chute_remote_pairs test_chute_remote_pairs)
add_test(w_wings test_w_wings)
add_test(xy_wings test_xy_wings)
add_test(xyz_wings test_xyz_wings)
add_test(swordfish test_swordfish)
