#ifndef SRC_SOLVER_STRATEGIES_H
#define SRC_SOLVER_STRATEGIES_H

typedef enum {
  NONE,
  FULL_HOUSE,
  NAKED_SINGLE,
  HIDDEN_SINGLE,
  LOCKED_CANDIDATE_POINTING,
  LOCKED_CANDIDATE_CLAIMING,
  HIDDEN_PAIRS,
  NAKED_PAIRS,
  HIDDEN_TRIPLES,
  NAKED_TRIPLES,
  HIDDEN_QUADS,
  NAKED_QUADS,
  X_WING,
  FINNED_X_WING,
  SWORDFISH,
  FINNED_SWORDFISH,
  JELLYFISH,
  FINNED_JELLYFISH,
  SKYSCRAPER,
  XY_WING,
  GUESS
} Strategy;

int getStrategyScore(Strategy strategy);

void getStrategyName(Strategy strategy, char* string);
#endif // SRC_SOLVER_STRATEGIES_H